name: GitHub Snake Game

on:
  # Planifier l’exécution du workflow chaque jour à minuit UTC
  schedule:
    - cron: "0 0 * * *"
  # Autoriser le déclenchement manuel du workflow
  workflow_dispatch:
  # Déclencher le workflow lors d’un push sur la branche principal
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Étape 1 : Récupérer le dépôt
      - name: Récupération du dépôt
        uses: actions/checkout@v3

      # Étape 2 : Générer les animations Snake
      - name: Générer les animations de contributions GitHub
        uses: Platane/snk@v3
        with:
          # Nom d’utilisateur GitHub pour l’animation
          github_user_name: ${{ github.repository_owner }}
          # Définir les fichiers de sortie avec leurs configurations
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Étape 3 : Déployer les fichiers générés dans la branche "output"
      - name: Déployer dans la branche Output
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          # Message de commit personnalisé (optionnel)
          commit_message: "Update snake animation [skip ci]"